application: crowdguru
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: guru.application

inbound_services:
- xmpp_message

libraries:
- name: jinja2
  version: latest
